version: 2

models:
  - name: dim_cities
    description: Data on cities with wheather measurements
    
    columns:
      - name: city
        description: City name (unique ID)
        tests:
          - unique
          - not_null

      - name: state
        description: State in which the city is located

      - name: country
        description: Country in which the city is located

      - name: latitude
        description: Latitude of the city
        tests:
          - dbt_utils.accepted_range:
              min_value: -90.0
              max_value: 90.0
              inclusive: true

      - name: longitude
        description: Longitude of the city
        tests:
          - dbt_utils.accepted_range:
              min_value: -180.0
              max_value: 180.0
              inclusive: true

      - name: timezone_offset
        description: Local time hours offset from UTC
        tests:
          - dbt_utils.accepted_range:
              min_value: -14.0
              max_value: 14.0
              inclusive: true


  - name: dim_stations
    description: Data on station sources for the wheather measurements
    
    columns:
      - name: station_id
        description: Unique identifier of the station
        tests:
          - unique
          - not_null

      - name: station_name
        description: Station name

      - name: latitude
        description: Station latitude
        tests:
          - dbt_utils.accepted_range:
              min_value: -90.0
              max_value: 90.0
              inclusive: true

      - name: longitude
        description: Station longitude
        tests:
          - dbt_utils.accepted_range:
              min_value: -180.0
              max_value: 180.0
              inclusive: true


  - name: fact_wheather_measurement
    description: Daily data on wheather measurements
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source("wheather_data", "wheather")

    columns:
      - name: fact_wheather_measurement_id		
        description: Unique id of the daiy measurement. Generate by hashing the concatenation of measurement_date and city_name
        tests:
          - unique
          - not_null
      
      - name: measurement_date		
        description: Date of the measurements
        tests:
          - not_null

      - name: max_temperature			
        description: Maximum temperature recorded (Celsius) 
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.9
              min_value: 0
              max_value: 40

      - name: min_temperature		
        description: Minimum temperature recorded (Celsius)
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.9
              min_value: 0
              max_value: 40
      
      - name: mean_temperature	
        description: Mean temperature (Celsius)
        tests:
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.9
              min_value: 0
              max_value: 40

      - name: max_apparent_temperarature
        description: Maximum apparent temperature (Celsius)
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.9
              min_value: 0
              max_value: 40

      - name: min_apparent_temperarature
        description: Minimum apparent temperature (Celsius)
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.9
              min_value: 0
              max_value: 40

      - name: mean_apparent_temperature
        description: Mean apparent temperature (Celsius)
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.9
              min_value: 0
              max_value: 40
      
      - name: relative_humidity
        description: Relative humidity (%)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              max_value: 100.0
              inclusive: true
      
      - name: precipitation
        description: Precipitation (mm)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              inclusive: true

      - name: precipitation_probability
        description: Precipitation chance (%)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              max_value: 100.0
              inclusive: true

      - name: precipitation_coverage
        description: Percentage of day in which precipitation was recorded (%)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              max_value: 100.0
              inclusive: true

      - name: precipitation_types
        description: Array of precipitation types recorded 

      - name: snow
        description: Snow precipitation (cm)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              inclusive: true

      - name: snow_depth
        description: Average amount of snow on the ground for the day (cm)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              inclusive: true

      - name: wind_gust
        description: The maximum wind speed measured over a short amount of time (KPH)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              inclusive: true

      - name: wind_speed
        description: Maximum wind speed recorded over the hourly measurements (KPH)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              inclusive: true

      - name: wind_direction
        description: Wind direction (degrees)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              max_value: 360.0
              inclusive: true

      - name: sea_level_pressure
        description: Sea level pressure (mb)
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.99
              min_value: 1000
              max_value: 1050
              config:
                severity: warn

      - name: cloud_coverage
        description: Percentage of the area covered by clouds (%)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              max_value: 100.0
              inclusive: true

      - name: visibility
        description: Maximum distance that can be seen in daylight (KM)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              inclusive: true

      - name: solar_radiation
        description: Maximum power recorded for the hourly measurements along the day (W/m2)

      - name: solar_energy
        description: Total energy build-up over the day (MJ/m2)

      - name: uv_index
        description: Indicates the level of exposure to UV radiation. Goes from 0 (no exposure) to 10 (high exposure)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.0
              max_value: 10.0
              inclusive: true

      - name: sunrise_time
        description: Time of sunrise in local time

      - name: sunset_time
        description: Time of sunset in local time

      - name: moon_phase	
        description: Phase of the moon (New Moon, Waxing Crescent, First Quarter, Waxing Gibbous, Full Moon, Waning Gibbous, Last Quarter, Waning Crescent) 
        tests:
          - accepted_values:
              values:
                - "New Moon"
                - "Waxing Crescent"
                - "First Quarter"
                - "Waxing Gibbous"
                - "Full Moon"
                - "Waning Gibbous"
                - "Last Quarter"
                - "Waning Crescent"

      - name: conditions
        description: Array of wheather conditions 

      - name: stations
        description: Array of wheather station sources

      - name: city_name
        description: Name of the city of the measurements
        tests:
          - not_null
    